[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/eula"
  to = "/eula.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
